theme: jekyll-theme-cayman
title: Welcome to Yike Liu's Homepage!
description: Maief student @ Brandeis, seeking for intern of Data Analyst！

follow:
    email:        yikel@brandeis.edu
    github:       https://github.com/yikeliu-echo
    linkedin:     https://www.linkedin.com/in/yikeliu/
